### ISSUE TITLE
perl -0777 is not supported for File::MimeInfo::Magic

### ISSUE THREAD

**Issue by mb-dbc-dk** [mbeijen/File-MimeInfo#18]
Hello.

When running (in a fresh 0.27 build directory): 
PERLRUN=$PWD/blib perl -MFile::MimeInfo::Magic -e 'print(mimetype($ARGV[0]), "\n")' Makefile.PL
I get as expected:
application/x-perl
when adding -0777:
PERLRUN=$PWD/blib perl -0777 -MFile::MimeInfo::Magic -e 'print(mimetype($ARGV[0]), "\n")' Makefile.PL
I get:
Magic file '/usr/share/mime/magic' doesn't seem to be a magic file at -e line 1.
text/plain

Which isn't exactly expected.
Yours
 Morten

**Comment by mbeijen** [comment]
with -0777 you change the input record separator for perl. This is great for one-liners but for more difficult code which uses modules, such as File::MimeInfo, not so much. File::MimeInfo uses the shared mime info datafiles and because you just changed the input record separator it can no longer properly read the data files.
