### ISSUE TITLE
Text file returned as video/mp2t

### ISSUE THREAD

**Issue by enricorox** [mbeijen/File-MimeInfo#50]
Hi!
For some reason `mimetype out.txt` returns `video/mp2t` instead of `text/plain`.
Removing 10 lines we get a text file.

The file is attached: [out.txt](https://github.com/mbeijen/File-MimeInfo/files/9705385/out.txt)

OS: Ubuntu 20.04
version: mimetype 0.29

**Comment by mbeijen** [comment]
Hi, thanks for opening your issue.
The problem is that the 'magic' tests are detecting your file as `video/mp2t`. You can check this with the `--debug --all` flags; the `--debug` provides you with more info about where the result was obtained from and the `--all` flag makes sure that all types of detection are used. 

By default, `mimetype` will try to use the mimeinfo database from freedesktop, that source correctly determines the file as being 'text'. You do not have the mimeinfo database installed, you can install it on Ubuntu using `apt install desktop-file-utils`. It is pre-installed with most graphical desktops on Ubuntu.

The magic database, which incorrectly labels the file as `video/mp2t`, is not part of this Perl module; it is used by the `file` command. However the `file` command uses different heuristics _before_ it tries to use the magic database, it uses a stat first.

I hope this helps... even if a little.

```
$ mimetype --debug --all  out.txt
> Data dirs are: /home/michiel/.local/share, /usr/share/gnome, /usr/local/share, /usr/share
> Checking inode type
> Checking globs for basename 'out.txt'
> Checking for extension '.txt'
out.txt: text/plain
> Checking all magic rules
> Value "G" at offset 5 matches at /usr/share/mime/magic line 1695
>> Value "G" at offset 197 matches at /usr/share/mime/magic line 1696
>>> Value "G" at offset 389 matches at /usr/share/mime/magic line 1697
>>>> Value "G" at offset 581 matches at /usr/share/mime/magic line 1698
>>>>> Value "G" at offset 773 matches at /usr/share/mime/magic line 1699
out.txt: video/mp2t
> File exists, trying default method
out.txt: text/plain
```
